name: Release next plugin version

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Fetch the tags for proper versioning
      run: git fetch --prune --unshallow --tags

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Make executable
      run: chmod +x gradlew

    - name: Mark next version
      run: ./gradlew release --no-daemon
