name: Build and publish plugin

on:
  workflow_dispatch:
  push:
    tags:
      - 'v0.*'
      - 'v1.*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Fetch the tags for proper versioning
      run: git fetch --prune --unshallow --tags -f

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'adopt'

    - name: Make executable
      run: chmod +x gradlew

    - name: Current version is
      run: ./gradlew currentVersion

    - name: Build plugin
      run: ./gradlew buildPlugin

    - name: Publish plugin to JB Plugins
      run: ./gradlew publishPlugin
      env:
        JB_PLUGINS_PUBLISH_TOKEN: ${{ secrets.JB_PLUGINS_PUBLISH_TOKEN }}
        # todo plugin signing
