# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build and publish plugin

on:
  workflow_dispatch:
# fixme relase and push in one step, can't leave as-is, as it'll break GH actions execution due to versions mismatch
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow --tags

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Make executable
      run: chmod +x gradlew

    - name: Build plugin
      run: ./gradlew buildPlugin

    - name: Publish plugin to JB Plugins
      run: ./gradlew currentVersion publishPlugin
      env:
        JB_PLUGINS_PUBLISH_TOKEN: ${{ secrets.JB_PLUGINS_PUBLISH_TOKEN }}
        # todo plugin signing
